# Generated by Django 3.0.4 on 2021-01-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invest_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('amount', models.FloatField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('invest_id', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('intrest', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('invest_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='transection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=250, null=True)),
                ('amount', models.FloatField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('status', models.CharField(default='FAILED', max_length=250)),
                ('details', models.CharField(max_length=250, null='TRUE')),
                ('message', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
