# Generated by Django 3.0.4 on 2021-01-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest_detail',
            name='investment',
            field=models.CharField(choices=[('running', 'running'), ('completed', 'completed')], default='running', max_length=200),
        ),
    ]
