# Generated by Django 3.0.4 on 2021-01-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210110_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest_detail',
            name='investment',
            field=models.CharField(choices=[('runing', 'runing'), ('completed', 'completed')], default='runing', max_length=200),
        ),
    ]
