# Generated by Django 3.0.4 on 2021-01-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210110_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest_detail',
            name='investment',
            field=models.CharField(default='runing', max_length=200),
        ),
    ]
