# Generated by Django 3.0.4 on 2021-01-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210110_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest_detail',
            name='refer_balance',
            field=models.FloatField(default='0.0', max_length=100),
        ),
        migrations.AddField(
            model_name='invest_detail',
            name='refer_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invest_detail',
            name='investment',
            field=models.CharField(default='running', max_length=200),
        ),
    ]
