# Generated by Django 3.0.4 on 2021-01-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_withdraws'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraws',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'success'), ('pending', 'pending'), ('rejected', 'rejected')], max_length=100, null=True),
        ),
    ]
