# Generated by Django 3.0.4 on 2021-01-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('balance', models.FloatField(default=0.0, max_length=250)),
                ('withdrawable_balance', models.FloatField(default=0.0, max_length=250)),
            ],
        ),
    ]
