# Generated by Django 3.0.4 on 2021-01-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='refer_balance',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='user_data',
            name='refer_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
